---
- name: Setup Ubuntu Server with Node.js v20, PM2, and Nginx
  hosts: ubuntu_servers
  become: yes

  vars:
    node_version: "20.x"

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - curl
          - gnupg
          - ca-certificates
          - build-essential
        state: present

    - name: Add NodeSource GPG key
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Add NodeSource repository
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main"
        state: present
        filename: nodesource

    - name: Update APT cache after adding NodeSource
      apt:
        update_cache: yes

    - name: Install Node.js v{{ node_version }}
      apt:
        name: nodejs
        state: present

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
